export const BUSINESS_CATEGORIES = {
  RESTAURANTS: [
    'Restaurant',
    'Fast Food',
    'Café',
    'Tea Shop',
    'Cloud Kitchen',
    'Catering',
  ],
  SHOPS: [
    'Bakery Shop',
    'Clothing Shop',
    'Electronics Shop',
    'Hardware Shop',
    'Pharmacy Shop',
  ],
  STORES: [
    'Supermarket',
    'Grocery Store',
    'Hypermarket',
    'Convenience Store',
    'Department Store',
  ],
  MANUFACTURING: [
    'Food Manufacturing',
    'Textile Manufacturing',
    'Garment Manufacturing',
    'Automotive Manufacturing',
    'Electronics Manufacturing',
    'General Manufacturing',
  ],
  WAREHOUSE: [
    'General Warehouse',
    'Cold Storage',
    'Raw Material Warehouse',
    'Finished Goods Warehouse',
    'E-commerce Warehouse',
  ],
  DISTRIBUTION: [
    'Food Distribution',
    'FMCG Distribution',
    'Textile Distribution',
    'Pharmaceutical Distribution',
    'Industrial Distribution',
  ],
  SERVICES: [
    'IT Services',
    'Automobile Workshop',
    'Repair Services',
    'Salon',
    'Cleaning Services',
    'Education',
    'Professional Services',
  ],
  HOTELS_LODGES: [
    'Hotel',
    'Resort',
    'Lodge',
    'Guest House',
    'Hostel',
    'Homestay',
  ],
};

export const CATEGORY_LABELS = {
  RESTAURANTS: 'Restaurants',
  SHOPS: 'Shops',
  STORES: 'Stores',
  MANUFACTURING: 'Manufacturing',
  WAREHOUSE: 'Warehouse',
  DISTRIBUTION: 'Distribution',
  SERVICES: 'Services',
  HOTELS_LODGES: 'Hotels & Lodges',
};
